import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  try {
    if (await readFile(path, 'utf8') === contents) return
  } catch {
    // Missing files are written below.
  }
  await writeFile(path, contents, 'utf8')
}

export async function generateBlueprintTypes(projectRoot: string): Promise<void> {
  const collectionsDir = join(projectRoot, 'src/vulse/collections')
  let files: string[]
  try {
    files = (await readdir(collectionsDir)).filter((f) => f.endsWith('.ts'))
  } catch {
    files = []
  }

  const names = files.map((f) => f.replace(/\.ts$/, ''))

  const out = `// Auto-generated by Vulse. Do not edit.
declare module 'vulse/server' {
  interface VulseCollections {
${names.map((n) => `    ${n}: any  // refined post-load`).join('\n')}
  }
}

declare module 'astro:content' {
  type VulseSlugs = ${names.length > 0 ? names.map((n) => `'${n}'`).join(' | ') : 'string'}
}
`
  await mkdir(join(projectRoot, '.vulse'), { recursive: true })
  await writeFileIfChanged(join(projectRoot, '.vulse/types.d.ts'), out)
}
