export const VULSE_VERSION = '0.0.0'
export { defineCollection, z } from './core/blueprints/define.js'
export { blocks, media, ref } from './core/blueprints/zod-helpers.js'
export type { Blueprint, Role, AuthContext, AccessArgs, AccessFn } from './core/blueprints/types.js'
export type { Block, BlockType } from './core/blocks/schema.js'
export { BUILT_IN_BLOCK_TYPES } from './core/blocks/schema.js'
