import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const jsPath = join(root, 'src/server/assets/live-preview-bridge.js')
const outPath = join(root, 'src/server/assets/live-preview-bridge.content.ts')

const content = readFileSync(jsPath, 'utf8')
writeFileSync(
  outPath,
  `// Generated by build:bridge — do not edit\nexport const livePreviewBridgeSource = ${JSON.stringify(content)}\n`,
)
