// Embeds the repo-root `themes/<key>/files/**` source trees into a generated TS
// module so the package can ship them and the CLI can write them into a user's
// project without filesystem access at install time. Mirrors sync-schema-templates.mjs.
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = join(pkgRoot, '..', '..')
const sourceDir = join(repoRoot, 'themes')
const outPath = join(pkgRoot, 'src/core/themes/themes.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name)
    if (statSync(abs).isDirectory()) out.push(...walk(abs))
    else out.push(abs)
  }
  return out
}

const themes = readdirSync(sourceDir)
  .filter((d) => statSync(join(sourceDir, d)).isDirectory())
  .sort()
  .map((key) => {
    const themeDir = join(sourceDir, key)
    const manifest = JSON.parse(readFileSync(join(themeDir, 'theme.json'), 'utf8'))
    const filesDir = join(themeDir, 'files')
    const files = walk(filesDir)
      .sort()
      .map((abs) => ({
        // Project-relative, POSIX-style path regardless of host OS.
        path: relative(filesDir, abs).split(sep).join('/'),
        content: readFileSync(abs, 'utf8'),
      }))
    return {
      key,
      name: typeof manifest.name === 'string' ? manifest.name : key,
      description: typeof manifest.description === 'string' ? manifest.description : '',
      files,
    }
  })

const body = `// Generated by sync-themes — do not edit.
// Source: themes/<key>/ at the repo root.

export interface ThemeFile {
  path: string
  content: string
}

export interface Theme {
  key: string
  name: string
  description: string
  files: ThemeFile[]
}

export const THEMES: Theme[] = ${JSON.stringify(themes, null, 2)}
`

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, body)
console.log(`sync-themes: embedded ${themes.length} theme(s) -> ${outPath}`)
