import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const versionLiteral = JSON.stringify(pkg.version)
const versionSource = `// Generated by sync-version — do not edit\nexport const VULSE_VERSION = ${versionLiteral}\n`
const versionTypes = `// Generated by sync-version — do not edit\nexport declare const VULSE_VERSION: string\n`
writeFileSync(join(root, 'src/version.ts'), versionSource)
// Admin SSR loads src/server/*.ts from node_modules; workerd resolves .js imports literally.
writeFileSync(join(root, 'src/server/version.js'), versionSource)
writeFileSync(join(root, 'src/server/version.d.ts'), versionTypes)
