// Generated by sync-schema-templates — do not edit.
// Source: schema-definitions/*.json at the repo root.

export interface SchemaTemplate {
  key: string
  name: string
  description: string
  handles: string[]
  bundle: unknown
}

export const SCHEMA_TEMPLATES: SchemaTemplate[] = [
  {
    "key": "documentation-site",
    "name": "Documentation site",
    "description": "Structured product/technical documentation: pages grouped into sections, written by authors.",
    "handles": [
      "author",
      "documentation_section",
      "documentation_page"
    ],
    "bundle": {
      "version": 1,
      "name": "Documentation site",
      "description": "Structured product/technical documentation: pages grouped into sections, written by authors.",
      "blueprints": [
        {
          "handle": "author",
          "label": "Author",
          "singleton": false,
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "avatar",
              "label": "Avatar",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "documentation_section",
          "label": "Documentation section",
          "singleton": false,
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "icon",
              "label": "Icon",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "order",
              "label": "Order",
              "ui": {
                "kind": "text"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "documentation_page",
          "label": "Documentation page",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "summary",
            "ogImage": "cover_image"
          },
          "preview": {
            "path": "/docs/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "cover_image",
              "label": "Cover image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "category",
              "label": "Category",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "getting-started",
                    "label": "Getting started"
                  },
                  {
                    "key": "guides",
                    "label": "Guides"
                  },
                  {
                    "key": "api-reference",
                    "label": "API reference"
                  },
                  {
                    "key": "tutorials",
                    "label": "Tutorials"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "section",
              "label": "Section",
              "ui": {
                "kind": "relationship",
                "to": "documentation_section"
              },
              "optional": true
            },
            {
              "name": "author",
              "label": "Author",
              "ui": {
                "kind": "relationship",
                "to": "author"
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Body",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  },
  {
    "key": "education",
    "name": "Education",
    "description": "Online learning platform: instructors, courses grouped by category, and lessons within courses.",
    "handles": [
      "instructor",
      "course_category",
      "course",
      "lesson"
    ],
    "bundle": {
      "version": 1,
      "name": "Education",
      "description": "Online learning platform: instructors, courses grouped by category, and lessons within courses.",
      "blueprints": [
        {
          "handle": "instructor",
          "label": "Instructor",
          "singleton": false,
          "preview": {
            "path": "/instructors/{slug}"
          },
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "photo",
              "label": "Photo",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "expertise",
              "label": "Expertise",
              "ui": {
                "kind": "select",
                "multiple": true,
                "options": [
                  {
                    "key": "design",
                    "label": "Design"
                  },
                  {
                    "key": "development",
                    "label": "Development"
                  },
                  {
                    "key": "business",
                    "label": "Business"
                  },
                  {
                    "key": "marketing",
                    "label": "Marketing"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "blocks"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "course_category",
          "label": "Course category",
          "singleton": false,
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "course",
          "label": "Course",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "summary",
            "ogImage": "cover_image"
          },
          "preview": {
            "path": "/courses/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "cover_image",
              "label": "Cover image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "level",
              "label": "Level",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "beginner",
                    "label": "Beginner"
                  },
                  {
                    "key": "intermediate",
                    "label": "Intermediate"
                  },
                  {
                    "key": "advanced",
                    "label": "Advanced"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "duration",
              "label": "Duration",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "category",
              "label": "Category",
              "ui": {
                "kind": "relationship",
                "to": "course_category"
              },
              "optional": true
            },
            {
              "name": "instructor",
              "label": "Instructor",
              "ui": {
                "kind": "relationship",
                "to": "instructor"
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Overview",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        },
        {
          "handle": "lesson",
          "label": "Lesson",
          "singleton": false,
          "drafts": true,
          "preview": {
            "path": "/lessons/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "course",
              "label": "Course",
              "ui": {
                "kind": "relationship",
                "to": "course"
              },
              "optional": true
            },
            {
              "name": "order",
              "label": "Order",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "duration",
              "label": "Duration",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "video",
              "label": "Video",
              "ui": {
                "kind": "link"
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Content",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  },
  {
    "key": "health-wellness",
    "name": "Health & wellness",
    "description": "Clinic/wellness site: practitioners, the services they offer, educational articles, and testimonials.",
    "handles": [
      "practitioner",
      "service",
      "wellness_article",
      "testimonial"
    ],
    "bundle": {
      "version": 1,
      "name": "Health & wellness",
      "description": "Clinic/wellness site: practitioners, the services they offer, educational articles, and testimonials.",
      "blueprints": [
        {
          "handle": "practitioner",
          "label": "Practitioner",
          "singleton": false,
          "preview": {
            "path": "/team/{slug}"
          },
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "photo",
              "label": "Photo",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "specialties",
              "label": "Specialties",
              "ui": {
                "kind": "select",
                "multiple": true,
                "options": [
                  {
                    "key": "nutrition",
                    "label": "Nutrition"
                  },
                  {
                    "key": "physiotherapy",
                    "label": "Physiotherapy"
                  },
                  {
                    "key": "mental-health",
                    "label": "Mental health"
                  },
                  {
                    "key": "general",
                    "label": "General practice"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "blocks"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "service",
          "label": "Service",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "preview": {
            "path": "/services/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "image",
              "label": "Image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "duration",
              "label": "Duration",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "30m",
                    "label": "30 minutes"
                  },
                  {
                    "key": "60m",
                    "label": "60 minutes"
                  },
                  {
                    "key": "90m",
                    "label": "90 minutes"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "price",
              "label": "Price",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "practitioner",
              "label": "Practitioner",
              "ui": {
                "kind": "relationship",
                "to": "practitioner"
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Details",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        },
        {
          "handle": "wellness_article",
          "label": "Wellness article",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "excerpt",
            "ogImage": "cover_image"
          },
          "preview": {
            "path": "/articles/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "excerpt",
              "label": "Excerpt",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "cover_image",
              "label": "Cover image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "published_at",
              "label": "Published at",
              "ui": {
                "kind": "date"
              },
              "optional": true
            },
            {
              "name": "category",
              "label": "Category",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "nutrition",
                    "label": "Nutrition"
                  },
                  {
                    "key": "fitness",
                    "label": "Fitness"
                  },
                  {
                    "key": "mental-health",
                    "label": "Mental health"
                  },
                  {
                    "key": "lifestyle",
                    "label": "Lifestyle"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "author",
              "label": "Author",
              "ui": {
                "kind": "relationship",
                "to": "practitioner"
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Body",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        },
        {
          "handle": "testimonial",
          "label": "Testimonial",
          "singleton": false,
          "fields": [
            {
              "name": "author_name",
              "label": "Author name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "quote",
              "label": "Quote",
              "ui": {
                "kind": "textarea"
              },
              "optional": false
            },
            {
              "name": "photo",
              "label": "Photo",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "rating",
              "label": "Rating",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "5",
                    "label": "5 stars"
                  },
                  {
                    "key": "4",
                    "label": "4 stars"
                  },
                  {
                    "key": "3",
                    "label": "3 stars"
                  },
                  {
                    "key": "2",
                    "label": "2 stars"
                  },
                  {
                    "key": "1",
                    "label": "1 star"
                  }
                ]
              },
              "optional": true
            }
          ]
        }
      ]
    }
  },
  {
    "key": "podcast",
    "name": "Podcast",
    "description": "A podcast site: hosts and episodes with audio, show notes, and per-episode guests.",
    "handles": [
      "host",
      "podcast_episode"
    ],
    "bundle": {
      "version": 1,
      "name": "Podcast",
      "description": "A podcast site: hosts and episodes with audio, show notes, and per-episode guests.",
      "blueprints": [
        {
          "handle": "host",
          "label": "Host",
          "singleton": false,
          "preview": {
            "path": "/hosts/{slug}"
          },
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "photo",
              "label": "Photo",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "social_links",
              "label": "Social links",
              "ui": {
                "kind": "grid",
                "mode": "table",
                "addLabel": "Add link",
                "fields": [
                  {
                    "name": "platform",
                    "label": "Platform",
                    "ui": {
                      "kind": "select",
                      "options": [
                        {
                          "key": "x",
                          "label": "X / Twitter"
                        },
                        {
                          "key": "instagram",
                          "label": "Instagram"
                        },
                        {
                          "key": "youtube",
                          "label": "YouTube"
                        },
                        {
                          "key": "website",
                          "label": "Website"
                        }
                      ]
                    },
                    "optional": false
                  },
                  {
                    "name": "url",
                    "label": "URL",
                    "ui": {
                      "kind": "link"
                    },
                    "optional": false
                  }
                ]
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "podcast_episode",
          "label": "Podcast episode",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "description",
            "ogImage": "cover_image"
          },
          "preview": {
            "path": "/episodes/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "episode_number",
              "label": "Episode number",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "season",
              "label": "Season",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "cover_image",
              "label": "Cover image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "audio",
              "label": "Audio",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "published_at",
              "label": "Published at",
              "ui": {
                "kind": "date"
              },
              "optional": true
            },
            {
              "name": "duration",
              "label": "Duration",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "hosts",
              "label": "Hosts",
              "ui": {
                "kind": "entries",
                "collections": [
                  "host"
                ]
              },
              "optional": true
            },
            {
              "name": "guests",
              "label": "Guests",
              "ui": {
                "kind": "grid",
                "mode": "stacked",
                "addLabel": "Add guest",
                "fields": [
                  {
                    "name": "name",
                    "label": "Name",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": false
                  },
                  {
                    "name": "bio",
                    "label": "Bio",
                    "ui": {
                      "kind": "textarea"
                    },
                    "optional": true
                  },
                  {
                    "name": "photo",
                    "label": "Photo",
                    "ui": {
                      "kind": "asset"
                    },
                    "optional": true
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "show_notes",
              "label": "Show notes",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  },
  {
    "key": "product-portfolio",
    "name": "Product portfolio",
    "description": "A catalog of products organized by category, each with a gallery and specifications.",
    "handles": [
      "product_category",
      "product"
    ],
    "bundle": {
      "version": 1,
      "name": "Product portfolio",
      "description": "A catalog of products organized by category, each with a gallery and specifications.",
      "blueprints": [
        {
          "handle": "product_category",
          "label": "Product category",
          "singleton": false,
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "image",
              "label": "Image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "product",
          "label": "Product",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "summary",
            "ogImage": "featured_image"
          },
          "preview": {
            "path": "/products/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "featured_image",
              "label": "Featured image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "price",
              "label": "Price",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "category",
              "label": "Category",
              "ui": {
                "kind": "relationship",
                "to": "product_category"
              },
              "optional": true
            },
            {
              "name": "featured",
              "label": "Featured",
              "ui": {
                "kind": "boolean"
              },
              "optional": true
            },
            {
              "name": "tags",
              "label": "Tags",
              "ui": {
                "kind": "select",
                "multiple": true,
                "clearable": true,
                "options": [
                  {
                    "key": "new",
                    "label": "New"
                  },
                  {
                    "key": "bestseller",
                    "label": "Bestseller"
                  },
                  {
                    "key": "limited",
                    "label": "Limited edition"
                  },
                  {
                    "key": "sale",
                    "label": "On sale"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "gallery",
              "label": "Gallery",
              "ui": {
                "kind": "grid",
                "mode": "stacked",
                "addLabel": "Add image",
                "fields": [
                  {
                    "name": "image",
                    "label": "Image",
                    "ui": {
                      "kind": "asset"
                    },
                    "optional": false
                  },
                  {
                    "name": "alt",
                    "label": "Alt text",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": true
                  },
                  {
                    "name": "caption",
                    "label": "Caption",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": true
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "specs",
              "label": "Specifications",
              "ui": {
                "kind": "grid",
                "mode": "table",
                "addLabel": "Add spec",
                "fields": [
                  {
                    "name": "label",
                    "label": "Label",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": false
                  },
                  {
                    "name": "value",
                    "label": "Value",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": false
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Description",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  },
  {
    "key": "real-estate",
    "name": "Real estate",
    "description": "Property listings with agents and neighborhoods, including galleries and listing metadata.",
    "handles": [
      "agent",
      "neighborhood",
      "property"
    ],
    "bundle": {
      "version": 1,
      "name": "Real estate",
      "description": "Property listings with agents and neighborhoods, including galleries and listing metadata.",
      "blueprints": [
        {
          "handle": "agent",
          "label": "Agent",
          "singleton": false,
          "preview": {
            "path": "/agents/{slug}"
          },
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "photo",
              "label": "Photo",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "phone",
              "label": "Phone",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "email",
              "label": "Email",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "neighborhood",
          "label": "Neighborhood",
          "singleton": false,
          "preview": {
            "path": "/neighborhoods/{slug}"
          },
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "image",
              "label": "Image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "property",
          "label": "Property",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "seoMapping": {
            "metaTitle": "title",
            "metaDescription": "summary",
            "ogImage": "featured_image"
          },
          "preview": {
            "path": "/properties/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "featured_image",
              "label": "Featured image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "price",
              "label": "Price",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "status",
              "label": "Status",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "for-sale",
                    "label": "For sale"
                  },
                  {
                    "key": "for-rent",
                    "label": "For rent"
                  },
                  {
                    "key": "pending",
                    "label": "Pending"
                  },
                  {
                    "key": "sold",
                    "label": "Sold"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "property_type",
              "label": "Property type",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "house",
                    "label": "House"
                  },
                  {
                    "key": "apartment",
                    "label": "Apartment"
                  },
                  {
                    "key": "condo",
                    "label": "Condo"
                  },
                  {
                    "key": "land",
                    "label": "Land"
                  },
                  {
                    "key": "commercial",
                    "label": "Commercial"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "bedrooms",
              "label": "Bedrooms",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "bathrooms",
              "label": "Bathrooms",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "area",
              "label": "Area",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "address",
              "label": "Address",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "featured",
              "label": "Featured",
              "ui": {
                "kind": "boolean"
              },
              "optional": true
            },
            {
              "name": "agent",
              "label": "Agent",
              "ui": {
                "kind": "relationship",
                "to": "agent"
              },
              "optional": true
            },
            {
              "name": "neighborhood",
              "label": "Neighborhood",
              "ui": {
                "kind": "relationship",
                "to": "neighborhood"
              },
              "optional": true
            },
            {
              "name": "gallery",
              "label": "Gallery",
              "ui": {
                "kind": "grid",
                "mode": "stacked",
                "addLabel": "Add photo",
                "fields": [
                  {
                    "name": "image",
                    "label": "Image",
                    "ui": {
                      "kind": "asset"
                    },
                    "optional": false
                  },
                  {
                    "name": "caption",
                    "label": "Caption",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": true
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "amenities",
              "label": "Amenities",
              "ui": {
                "kind": "select",
                "multiple": true,
                "options": [
                  {
                    "key": "parking",
                    "label": "Parking"
                  },
                  {
                    "key": "pool",
                    "label": "Pool"
                  },
                  {
                    "key": "garden",
                    "label": "Garden"
                  },
                  {
                    "key": "gym",
                    "label": "Gym"
                  },
                  {
                    "key": "balcony",
                    "label": "Balcony"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Description",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  },
  {
    "key": "saas-platform",
    "name": "SaaS platform",
    "description": "Marketing & product content for a SaaS: team, features, pricing plans, and a changelog.",
    "handles": [
      "team_member",
      "feature",
      "pricing_plan",
      "changelog_entry"
    ],
    "bundle": {
      "version": 1,
      "name": "SaaS platform",
      "description": "Marketing & product content for a SaaS: team, features, pricing plans, and a changelog.",
      "blueprints": [
        {
          "handle": "team_member",
          "label": "Team member",
          "singleton": false,
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "role",
              "label": "Role",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "bio",
              "label": "Bio",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "avatar",
              "label": "Avatar",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "linkedin",
              "label": "LinkedIn",
              "ui": {
                "kind": "link"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "feature",
          "label": "Feature",
          "singleton": false,
          "drafts": true,
          "seo": true,
          "preview": {
            "path": "/features/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "summary",
              "label": "Summary",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "icon",
              "label": "Icon",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "image",
              "label": "Image",
              "ui": {
                "kind": "asset"
              },
              "optional": true
            },
            {
              "name": "category",
              "label": "Category",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "core",
                    "label": "Core"
                  },
                  {
                    "key": "collaboration",
                    "label": "Collaboration"
                  },
                  {
                    "key": "security",
                    "label": "Security"
                  },
                  {
                    "key": "integrations",
                    "label": "Integrations"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Body",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        },
        {
          "handle": "pricing_plan",
          "label": "Pricing plan",
          "singleton": false,
          "fields": [
            {
              "name": "name",
              "label": "Name",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "price",
              "label": "Price",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "billing_period",
              "label": "Billing period",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "monthly",
                    "label": "Monthly"
                  },
                  {
                    "key": "yearly",
                    "label": "Yearly"
                  },
                  {
                    "key": "one-time",
                    "label": "One-time"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "description",
              "label": "Description",
              "ui": {
                "kind": "textarea"
              },
              "optional": true
            },
            {
              "name": "highlighted",
              "label": "Highlighted",
              "ui": {
                "kind": "boolean"
              },
              "optional": true
            },
            {
              "name": "plan_features",
              "label": "Plan features",
              "ui": {
                "kind": "grid",
                "mode": "table",
                "addLabel": "Add feature",
                "fields": [
                  {
                    "name": "label",
                    "label": "Feature",
                    "ui": {
                      "kind": "text"
                    },
                    "optional": false
                  },
                  {
                    "name": "included",
                    "label": "Included",
                    "ui": {
                      "kind": "boolean"
                    },
                    "optional": true
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "cta_label",
              "label": "CTA label",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "cta_link",
              "label": "CTA link",
              "ui": {
                "kind": "link"
              },
              "optional": true
            }
          ]
        },
        {
          "handle": "changelog_entry",
          "label": "Changelog entry",
          "singleton": false,
          "drafts": true,
          "preview": {
            "path": "/changelog/{slug}"
          },
          "fields": [
            {
              "name": "title",
              "label": "Title",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "slug",
              "label": "Slug",
              "ui": {
                "kind": "text"
              },
              "optional": false
            },
            {
              "name": "version",
              "label": "Version",
              "ui": {
                "kind": "text"
              },
              "optional": true
            },
            {
              "name": "released_at",
              "label": "Released at",
              "ui": {
                "kind": "date"
              },
              "optional": true
            },
            {
              "name": "type",
              "label": "Type",
              "ui": {
                "kind": "select",
                "options": [
                  {
                    "key": "added",
                    "label": "Added"
                  },
                  {
                    "key": "changed",
                    "label": "Changed"
                  },
                  {
                    "key": "fixed",
                    "label": "Fixed"
                  },
                  {
                    "key": "removed",
                    "label": "Removed"
                  }
                ]
              },
              "optional": true
            },
            {
              "name": "body",
              "label": "Body",
              "ui": {
                "kind": "blocks"
              },
              "optional": false
            }
          ]
        }
      ]
    }
  }
]
